import React from 'react';
import PropTypes from 'prop-types';
import { Header, Jumbotron } from 'watson-react-components';

const demoName = 'Whoopy';
const DESCRIPTION = 'Welcome to the future !';

export default function Layout(props) {
  return (
    <html lang="en">
      <head>
        <title>{demoName}</title>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="og:title" content={demoName} />
        <meta name="og:description" content={DESCRIPTION} />
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="/css/watson-react-components.min.css" />
        <link rel="stylesheet" href="/css/style.css" />
        <style date-aphrodite>{props.css.content}</style>
        <script type="text/javascript" src="scripts/bundle.js" defer async />
      </head>
      <body>
        <div id="bande">
          <label class="topleft">Whoopy DOC</label>
          <img src="../images/DSILogo.jpg" class="topright" alt="logo DSI DIFFUSION"></img>
        </div>
        <div>
          <h3>
            Bienvenue dans Whoopy DOC
          </h3>
        </div>
        <div id="dsilogo"></div>
        <div id="root">
          {props.children}
        </div>
        <script type="text/javascript" src="scripts/bundle.js" />
        { props.bluemixAnalytics ?
          <script type="text/javascript" src="scripts/analytics.js" /> : null }
      </body>
    </html>
  );
}

Layout.propTypes = {
  children: PropTypes.object.isRequired,
  css: PropTypes.object.isRequired, // attaching css generated by aphrodite
  bluemixAnalytics: PropTypes.bool.isRequired,
};


/*
<Header
          mainBreadcrumbs={demoName}
          mainBreadcrumbsUrl="https://www.ibm.com/watson/services/natural-language-understanding/"
          subBreadcrumbs="Demo"
          subBreadcrumbsUrl="https://natural-language-understanding-demo.mybluemix.net"
        />
  <Jumbotron
    serviceName={demoName}
    repository="https://github.com/watson-developer-cloud/natural-language-understanding-nodejs"
    documentation="https://console.bluemix.net/docs/services/natural-language-understanding/getting-started.html"
    apiReference="http://www.ibm.com/watson/developercloud/natural-language-understanding/api"
    version="GA"
    startInBluemix="https://console.bluemix.net/registration?target=%2Fdeveloper%2Fwatson%2Fcreate-project%3Fservices%3Dnatural-language-understanding%26hideTours%3Dtrue&cm_mmc%3DOSocial_Tumblr-_-Watson%2BCore_Watson%2BCore%2B-%2BPlatform-_-WW_WW-_-wdc-ref%26cm_mmc%3DOSocial_Tumblr-_-Watson%2BCore_Watson%2BCore%2B-%2BPlatform-_-WW_WW-_-wdc-ref%26cm_mmca1%3D000000OF%26cm_mmca2%3D10000409"
    description={DESCRIPTION}
  />
*/